name: Build and Push Multiarch Docker Image

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ghcr.io/qxzcr/zadanie2
  CACHE_NAME: ghcr.io/qxzcr/zadanie2-cache

jobs:
  build-and-push:
    name: Build & Push to GHCR
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true               # пушить образ в GHCR
        load: true               # завантажити образ локально для Trivy
        platforms: linux/amd64,linux/arm64
        tags: ${{ env.IMAGE_NAME }}:latest
        cache-from: type=registry,ref=${{ env.CACHE_NAME }}:latest
        cache-to: type=registry,ref=${{ env.CACHE_NAME }}:latest,mode=max

    - name: Scan for vulnerabilities
      uses: aquasecurity/trivy-action@0.11.2
      with:
        image-ref: ${{ env.IMAGE_NAME }}:latest
        format: table
        severity: CRITICAL,HIGH
        exit-code: 1
        ignore-unfixed: true
        github-token: ${{ secrets.CR_PAT }}  # важливо для авторизації при скануванні приватних образів
